Add more robust IPv6 support
woohgit/ansible-role-teleport pull request #6
Opened 2018-03-04 00:55 UTC by CFSworks

Hi! Thank you so much for developing this Ansible role; it's quite useful!

I use IPv6 heavily in my cluster and Teleport's YAML parser tends not to like it when an unquoted string begins with `[`, so I've added quotes around the variables in the `teleport.yaml.j2` template likely to begin with strange characters.

The second commit in this PR adds a new config variable to make it a bit easier to switch on IPv6 by default. (Noting, of course, that Gravitational still doesn't promise official Teleport IPv6 support - but it is quite good in my experience.)

2018-05-17 22:01 UTC, woohgit commented
Hey,

Thanks! This is a nice feature.

Can you please make sure that you adjust the requirements and the tests too, because right now it's depending on a python package (python-netaddr) and since it's not installed the tests are failing. 

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleFilterError: {{ teleport_default_address | ipwrap }}:3023: The ipwrap filter requires python-netaddr be installed on the ansible controller"
```

2018-05-17 22:02 UTC, woohgit requested changes
Can you please make sure that you adjust the requirements and the tests too, because right now it's depending on a python package (python-netaddr) and since it's not installed the tests are failing.

2018-05-23 20:30 UTC, CFSworks commented
@woohgit Thanks for the feedback! I didn't notice the Travis-CI job fail, or I'd have taken care of that already.

I've made the necessary changes; tests pass; should be good to merge!

2018-05-23 23:50 UTC, woohgit commented
@CFSworks  Thanks for the fixes! 

Just one more thing. This role is now depending on a 3rd party python dependency which is not installed by default on the systems. We should let the users know that this role needs this python-netaddr package. So Please add it to the README so they won't miss it and won't be surprised that suddenly the role stopped working without any mention.

2018-05-24 00:07 UTC, CFSworks commented
Just filled in the "Dependencies" section of the README.

I also looked and it seems there's no way to record the dependency in `meta/main.yml` correct? If possible I'd like to mention it there too.

2018-05-24 00:57 UTC, woohgit commented
@CFSworks  Yeah it seems we can only do it in the README. If we were in the ansible module itself, we could check that, but that would only throw the same exception we have right now when it's not installed so I think it's good to go. Thanks!

2018-05-24 00:58 UTC, merged